### ISSUE TITLE
音乐库更新音乐数据后再同步专辑数据会异常地慢

### ISSUE THREAD

**Issue by Pitaya-ligang** [gitbobobo/StreamMusic#443]
**Describe the bug (BUG 描述)**
音乐库更新音乐数据后再同步专辑数据会异常地慢

**To Reproduce (复现步骤)**
1. 在emby库里更新音乐
2. 打开音流，查看更新进度
3. 观察专辑数据的进度

**Expected behavior (期望行为)**
目前同步专辑数据 每1000需要3-4分钟，之前是没这么久的

**Screenshots (截图)**
![20240726-181500](https://github.com/user-attachments/assets/cc4c1ee7-419f-4d36-a681-9e52600635c1)

**Platform and Device Info (操作系统及设备信息)**
ios和安卓都是

**Music Server Type (音乐服务器类型)**
emby 4.9.0.27

**Additional context (额外信息)**
之前的账号还能测试

**Comment by Pitaya-ligang** [comment]
*** Error Report ***
        Version: [4.9.0.27](http://4.9.0.27/)
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 4.4.302+ (root@build6) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:01:14 CST 2024
        OS/Process: x64/x64
        Framework: .NET 8.0.6
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /config
        Application path: /system
        MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: The SSL connection could not be established, see inner exception.
         ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
         ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
           at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
           at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
           at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
           --- End of inner exception stack trace ---
           at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
           at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
           --- End of inner exception stack trace ---
        Source: 
        TargetSite: 
        No Stack Trace Available
        InnerException: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
        Source: System.Net.Http
        TargetSite: Void MoveNext()
           at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
           at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
           at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
           at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
        InnerException: System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
        Source: System.Net.Security
        TargetSite: Void MoveNext()
           at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
           at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
           at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

emby报错信息

**Comment by gitbobobo** [comment]
嗯，我这里也很慢，我看看什么情况

**Comment by Pitaya-ligang** [comment]
我用1.3.1的包同步是解决了 但同步后更新的专辑点进去是空的呢。。

**Comment by gitbobobo** [comment]
我这里正常的

**Comment by Pitaya-ligang** [comment]
https://github.com/user-attachments/assets/efe1d778-e6f2-4c49-88c9-ec37624e7835

看看我的视频

**Comment by gitbobobo** [comment]
1.3.1正式版已经更新了，看下这个问题还存在不？

还是不行的话再发我一下测试账号吧，之前的邮件已经删掉了

**Comment by Pitaya-ligang** [comment]
已发送，需要说明的是 初次同步的数据是正常的，之后新增的才会出现问题。

**Comment by gitbobobo** [comment]
试了下视频中的问题并未出现，如果你说的是新增歌曲之后可能出现这种情况，那是有可能的，媒体库模式只会根据歌曲数量来判断是否需要更新歌曲，也就是只能新增歌曲，删除和修改歌曲都会导致本地数据和服务器数据出现偏差。

像你这么大的曲库，还是更推荐使用直连模式的。这是二者的区别 https://music.aqzscn.cn/docs/guides/sync_mode

**Comment by Pitaya-ligang** [comment]
好的 主要是直连模式下 搜索不会很精准  很多歌曲搜索不出来

**Comment by gitbobobo** [comment]
好像有Emby搜索增强插件，不清楚第三方软件是否依旧有效
